### ISSUE TITLE
t/04_auth/04_oauth2.t failing with new Net::Oauth2

### ISSUE THREAD

**Issue by samuelckaufman** [lopnor/Net-Google-DataAPI#2]
Heya, 
Just tried to install Net::Google::DataAPI, 
seems a new Net::OAuth2 just came out that took out ->authorize_url, which Net::Google::DataAPI depends on.
The test itself is checking for type == 'web_server' in the redirect_url but that is now gone from the Net::OAuth2::Profile::WebServer, and previously was marked legacy in the source:
https://metacpan.org/source/KGRENNAN/Net-OAuth2-0.07/lib/Net/OAuth2/Profile/WebServer.pm : 

  # legacy for pre v2.09 (37Signals)
  $options{type} = 'web_server';

I tweaked  Net::Google::DataAPI a bit to get it to work, you can see the patch here:
https://github.com/ediblenergy/Net-Google-DataAPI/compare/lopnor:master...authorize_url_to_authorize
seems to be working for me.

**Comment by lopnor** [comment]
thanks, got patch and pushed development version to CPAN. It will appear soon on:

http://search.cpan.org/~danjou/Net-Google-DataAPI-0.2802_1/

**Comment by lopnor** [comment]
failed again with Net::Auth2 0.52 and fixing....

**Comment by samuelckaufman** [comment]
Oh man, yeah looks like he's been rewriting large chunks of it.

**Comment by lopnor** [comment]
so sorry for make you waiting...
new version committed 869e1453e95d4dec4780e9ade9c8126dbe75fff2
this will fix it

**Comment by samuelckaufman** [comment]
Great!
