### ISSUE TITLE
Failure in t/04_auth/04_oauth2.t ('refresh_token' vs 'authorization_code')

### ISSUE THREAD

**Issue by pjf** [lopnor/Net-Google-DataAPI#4]
When building `Net::Google::DataAPI` v0.2802_1 (dev release) with `Net::OAuth2` v0.53, the `t/04_oauth/04_oauth2.t` test fails:

```
#   Failed test at t/04_auth/04_oauth2.t line 31.
#     Structures begin differing at:
#          $got->{grant_type} = 'refresh_token'
#     $expected->{grant_type} = 'authorization_code'

#   Failed test at t/04_auth/04_oauth2.t line 31.
#     Structures begin differing at:
#          $got->{grant_type} = 'refresh_token'
#     $expected->{grant_type} = 'authorization_code'
# Looks like you failed 2 tests of 32.
t/04_auth/04_oauth2.t ................... 
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/32 subtests 
```

I'm guessing this is from updates to how the `Net::OAuth2` module handles things internally, but I'm not sure if this is a harmless change (and we can just change the `is_deeply` test to look for the new strings), or actually significant.

Many thanks!

Paul

**Comment by lopnor** [comment]
pushed new dev version 869e1453e95d4dec4780e9ade9c8126dbe75fff2
it will appear below soon.
http://search.cpan.org/~danjou/Net-Google-DataAPI-0.2802_2/

**Comment by pjf** [comment]
Awesome, that passes all the tests on my machine!  Thank you! :)
